let defaults = [
    {left: 'ground', right: ['move', 'see']},
    {left: 'wall', right: ['stop', 'see']},
    {left: 'cliff', right: ['stop', 'blind']},
    {left: 'chasm', right: ['stop', 'see']},
    {left: 'trap', right: ['hurt immediately', 'hurt on turn start', 'move', 'see']},
    {left: 'fire', right: ['hurt on turn start', 'move', 'see']},
    {left: 'sand', right: ['move', 'slow*1', 'slow horse*2', 'see']},
    {left: 'stairs', right: ['move', 'slow*.5', 'slow horse*1', 'see']},
    {left: 'ice', right: ['move', 'slow*1.25', 'see']},
    {left: 'snow', right: ['move', 'slow*2', 'blind*.5']},
    {left: 'shallow_water', right: ['move', 'slow*1.5', 'slow horse*.5', 'see']},
    {left: 'deep_water', right: ['stop', 'see']},
    {left: 'locked_door', right: ['stop', 'blind', 'open']},
    {left: 'open_door', right: ['move', 'see']},
    {left: 'teleporter', right: ['move', 'see', 'warp']},
    {left: 'lever', right: ['move', 'see', 'use']},
    {left: 'switch', right: ['move', 'see', 'use']},
    {left: 'locked_chest', right: ['stop', 'see']},
    {left: 'open_chest', right: ['move', 'see']},
    {left: 'lava', right: ['stop', 'see']},
    {left: 'acid', right: ['stop', 'see']},
    {left: 'ranged_emplacement', right: ['move', 'see', 'arms']},
    {left: 'magic_emplacement', right: ['move', 'see', 'arms']},
    {left: 'heal', right: ['move', 'see', 'heal']},
    {left: 'stronghold', right: ['move', 'see', 'heal*1.5', 'guard*1.5', 'avoid*1']},
    {left: 'guard', right: ['move', 'see', 'guard*1']},
    {left: 'avoid', right: ['move', 'see', 'avoid*1']},
    {left: 'roof', right: ['stop', 'see']},
    {left: 'tallwall', right: ['stop', 'blind']},
    {left: 'shrubs', right: ['move', 'see', 'avoid*.5']},
    {left: 'bushes', right: ['move', 'slow*.5', 'see', 'avoid*1']},
    {left: 'trees', right: ['move', 'slow*1.5', 'see', 'avoid*1.5']},
    {left: 'boulder', right: ['stop', 'see']},
    {left: 'fence', right: ['stop', 'see']},
    {left: 'forest', right: ['move', 'slow*1.5', 'slow horse*2', 'blind*.5', 'avoid*2', 'hidden']},
    {left: 'fog', right: ['move', 'blind', 'stop if enemy', 'hidden']},
    {left: 'mist', right: ['move', 'blind*.5', 'stop if enemy']},
]

export default defaults