const defaults = {
    'unitsCanHaveChildren': true,
    'useExperienceSublevels': false,
    'useExperienceAptitudes': true,
    'unitEditorAvatarDefaultHairColor': 'rgb(39, 31, 86)',
    'unitEditorAvatarDefaultEyeColor': 'rgb(34, 132, 181)',
    'combatCombatArts': false,
    'combatCombatArtLimit': 3,
    'combatWeaponTriangle': true,
    'combatTriangleTypes': ["Sword", "Lance", "Axe", "Bow", "Gauntlet", "Dagger"],
    'combatNeutralTypes': [],
    'combatTriangleMapping': {},
    'combatExpandedWeaponTriangle': false,
    'combatWeaponTriangleAdvantage': 20,
    'combatWeaponTriangleDisadvantage': -20,
    'combatMagicTriangle': false,
    'combatMagicTriangleAdvantage': 20,
    'combatMagicTriangleDisadvantage': -20,
    'combatMagicTriangleTypes': [],
    'combatNeutralMagicTypes': [],
    'combatMagicTriangleMapping': {},
    'combatBattalions': true,
    'combatBattalionLimit': 1,
    'combatBattalionEndurance': true,
    'combatPairUp': false,
    'combatAdjutants': true,
    'combatAdjutantHeal': true,
    'combatAdjutantGuard': true,
    'combatAdjutantAttack': true,
    'aptitudeGoals': false,
    'statsUseExtraStatWeight': false,
    'statsExtraStatWeightAffectsMovement': false,
    'statsUseExtraStatLuck': true,
    'combatSeparateCritAvoid': false,
    'statsUseExtraStatAuthority': false,
    'statsUseExtraStatCharm': true,
    'statsAptitudesUseRiding': true,
    'statsAptitudesUseFlying': true,
    'statsAptitudesUseAuthority': false,
    'statsAptitudesUseArmor': false,
    'globalMagicTypes': [],
    'globalWeaponsTypes': [],
    'GameEditorWeaponTriangleFieldsTopCorner': [],
}

export default defaults
