const labels = {
        weaponsCanBeForged: 'Weapons can be forged',
        weaponsCanBeRepaired: 'Weapons can be repaired',
        unitsCanHaveChildren: 'Units can have children',
        useExperienceSublevels: 'Use experience sublevels',
        useExperienceAptitudes: 'Use experience aptitudes',
        combatCombatArts: 'Combat arts',
        combatWeaponTriangle: 'Weapon triangle',
        combatExpandedWeaponTriangle: 'Expanded weapon triangle',
        combatMagicTriangle: 'Magic triangle',
        combatBattalions: 'Battalions',
        combatBattalionEndurance: 'Battalion endurance',
        combatPairUp: 'Pair up',
        combatAdjutants: 'Adjutants',
        combatAdjutantHeal: 'Adjutant heal',
        combatAdjutantGuard: 'Adjutant guard',
        combatAdjutantAttack: 'Adjutant attack',
        statsUseExtraStatWeight: 'Use extra stat weight',
        statsExtraStatWeightAffectsMovement: 'Extra stat weight affects movement',
        statsUseExtraStatLuck: 'Use extra stat luck',
        combatSeparateCritAvoid: 'Separate crit avoid',
        statsUseExtraStatAuthority: 'Use extra stat authority',
        statsUseExtraStatCharm: 'Use extra stat charm',
        statsAptitudesUseRiding: 'Aptitudes use riding',
        statsAptitudesUseFlying: 'Aptitudes use flying',
        statsAptitudesUseAuthority: 'Aptitudes use authority',
        statsAptitudesUseArmor: 'Aptitudes use armor',
        combatCombatArtLimit: 'Combat art limit',
        combatWeaponTriangleAdvantage: 'Weapon triangle advantage',
        combatWeaponTriangleDisadvantage: 'Weapon triangle disadvantage',
        combatMagicTriangleAdvantage: 'Magic triangle advantage',
        combatMagicTriangleDisadvantage: 'Magic triangle disadvantage',
        combatBattalionLimit: 'Battalion limit',
        unitEditorAvatarDefaultHairColor: 'Avatar default hair color',
        unitEditorAvatarDefaultEyeColor: 'Avatar default eye color',
        combatTriangleMapping: 'Combat triangle mapping',
        combatMagicTriangleMapping: 'Combat magic triangle mapping',
        globalWeaponsTypes: 'Global weapons types',
        combatTriangleTypes: 'Combat triangle types',
        combatNeutralTypes: 'Combat neutral types',
        combatMagicTriangleTypes: 'Combat magic triangle types',
        combatNeutralMagicTypes: 'Combat neutral magic types',
        aptitudeGoals: '(Friendly/avatar) units have aptitude goals',
        UseWeatherOnLevels: 'Use weather on levels',
        unitEditorAvatarDefaultSkinColor: 'Avatar default skin color',
        unitEditorAvatarDefaultHairStyle: 'Avatar default hair style',
}

export default labels