const tooltips = {
    useExperienceSublevels: 'Use experience sublevels',
    useExperienceAptitudes: 'Use experience aptitudes',
    combatCombatArts: 'Combat arts',
    combatWeaponTriangle: 'Weapon triangle',
    combatExpandedWeaponTriangle: 'Expanded weapon triangle',
    combatMagicTriangle: 'Magic triangle',
    combatBattalions: 'Battalions',
    combatBattalionEndurance: 'Battalion endurance',
    combatPairUp: 'Pair up',
    combatAdjutants: 'Adjutants',
    statsExtraStatWeightAffectsMovement: 'Extra stat weight affects movement',
    combatSeparateCritAvoid: 'Separate crit avoid',
    combatWeaponTriangleAdvantage: 'Weapon triangle advantage',
    combatWeaponTriangleDisadvantage: 'Weapon triangle disadvantage',
    combatMagicTriangleAdvantage: 'Magic triangle advantage',
    combatMagicTriangleDisadvantage: 'Magic triangle disadvantage',
    combatTriangleMapping: 'Combat triangle mapping',
    combatMagicTriangleMapping: 'Combat magic triangle mapping',
    globalWeaponsTypes: 'Global weapons types',
    combatTriangleTypes: 'Combat triangle types',
    combatNeutralTypes: 'Combat neutral types',
    combatMagicTriangleTypes: 'Combat magic triangle types',
    combatNeutralMagicTypes: 'Combat neutral magic types',
}

export default tooltips